name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Create Config File
        run: |
          # Create Config.xcconfig with the actual API key
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" > ParentingAssistant/Config.xcconfig
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> ParentingAssistant/Config.xcconfig
          echo "PRODUCT_BUNDLE_IDENTIFIER=com.yourcompany.parentingassistant" >> ParentingAssistant/Config.xcconfig
          echo "PRODUCT_NAME=ParentingAssistant" >> ParentingAssistant/Config.xcconfig

      - name: Build
        run: |
          xcodebuild -scheme ParentingAssistant \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' \
            build

      - name: Archive App
        run: |
          xcodebuild -scheme ParentingAssistant \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' \
            archive -archivePath build/ParentingAssistant.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ParentingAssistant.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight@v1
        with:
          app-path: build/ParentingAssistant.ipa
          api-key: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          api-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          api-issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
