name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Add manual trigger

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
  APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
  APP_STORE_CONNECT_API_ISSUER: ${{ secrets.APP_STORE_CONNECT_API_ISSUER }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF"
          echo "Event: $GITHUB_EVENT_NAME"

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.0"

      - name: Create Config.xcconfig
        run: |
          echo "Creating Config.xcconfig..."
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" > ParentingAssistant/Config.xcconfig
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> ParentingAssistant/Config.xcconfig
          echo "PRODUCT_BUNDLE_IDENTIFIER=com.yourcompany.parentingassistant" >> ParentingAssistant/Config.xcconfig
          echo "PRODUCT_NAME=ParentingAssistant" >> ParentingAssistant/Config.xcconfig
          echo "Config.xcconfig created successfully"

      - name: List Directory Contents
        run: |
          echo "Listing contents of current directory:"
          ls -la
          echo "Listing contents of ParentingAssistant directory:"
          ls -la ParentingAssistant/

      - name: Build App
        run: |
          echo "Starting build process..."
          xcodebuild -project ParentingAssistant.xcodeproj \
                    -scheme ParentingAssistant \
                    -configuration Release \
                    -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
                    clean build | xcpretty

      - name: Archive App
        run: |
          echo "Starting archive process..."
          xcodebuild -project ParentingAssistant.xcodeproj \
                    -scheme ParentingAssistant \
                    -configuration Release \
                    -archivePath $RUNNER_TEMP/ParentingAssistant.xcarchive \
                    archive | xcpretty

      - name: Export IPA
        run: |
          echo "Starting IPA export process..."
          xcodebuild -exportArchive \
                    -archivePath $RUNNER_TEMP/ParentingAssistant.xcarchive \
                    -exportOptionsPlist exportOptions.plist \
                    -exportPath $RUNNER_TEMP/build | xcpretty

      - name: Upload IPA to TestFlight
        uses: apple-actions/download-provisioning-profiles@v1.0.0
        with:
          bundle-id: "ParentingAssistant.ParentingAssistant"
          issuer-id: ${{ secrets.APP_STORE_CONNECT_API_ISSUER }}
          api-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          api-private-key: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

      - name: Upload to TestFlight
        run: |
          echo "Starting TestFlight upload..."
          echo "Checking IPA file location..."
          ls -la "${{ runner.temp }}/build/"
          echo "Uploading to TestFlight..."
          xcrun altool --upload-app \
            --type ios \
            --file "${{ runner.temp }}/build/ParentingAssistant.ipa" \
            --apiKey "${{ secrets.APP_STORE_CONNECT_API_KEY }}" \
            --apiKeyId "${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}" \
            --apiIssuer "${{ secrets.APP_STORE_CONNECT_API_ISSUER }}"

      - name: Upload dSYM Files
        run: |
          echo "Starting dSYM upload process..."
          # Find all dSYM files in the archive
          find "$RUNNER_TEMP/ParentingAssistant.xcarchive/dSYMs" -name "*.dSYM" -print0 | while IFS= read -r -d '' dSYM; do
            echo "Uploading dSYM: $dSYM"
            # Upload to Firebase Crashlytics
            $RUNNER_TEMP/ParentingAssistant.xcarchive/Products/Applications/ParentingAssistant.app/Frameworks/FirebaseCrashlytics.framework/upload-symbols \
              -gsp "$RUNNER_TEMP/ParentingAssistant.xcarchive/Products/Applications/ParentingAssistant.app/GoogleService-Info.plist" \
              -p ios \
              "$dSYM"
          done
